name: Deploy Docs

on:
  pull_request:
    branches:
      - stable
      - master
  push:
    branches:
      - stable
      - master

jobs:
  doc:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install mdbook
        run: |
          mkdir mdbook
          curl -Lf https://github.com/rust-lang/mdBook/releases/download/v0.4.6/mdbook-v0.4.6-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
          echo "`pwd`/mdbook" >> $GITHUB_PATH
      - name: Build book
        run: |
          git checkout stable
          cd doc
          mdbook build
          mv book ${{ runner.temp }}
          git checkout master
          mdbook build
          mv book ${{ runner.temp }}/book/devel